import { Router, type Request, type Response } from 'express';
import Blog from '../models/Blog.js';

const router = Router();

// Get all blog posts
router.get('/', async (req: Request, res: Response) => {
  try {
    const { category, featured } = req.query;
    const query: any = {};
    
    if (category) {
      query.category = category;
    }
    
    if (featured === 'true') {
      query.isFeatured = true;
    }
    
    const blogs = await Blog.find(query).sort({ publishedAt: -1 });
    res.json(blogs);
  } catch (error) {
    res.status(500).json({ message: 'Error fetching blog posts', error });
  }
});

// Get a single blog post by slug
router.get('/:slug', async (req: Request, res: Response) => {
  try {
    const blog = await Blog.findOne({ slug: req.params.slug });
    if (!blog) {
      return res.status(404).json({ message: 'Blog post not found' });
    }
    res.json(blog);
  } catch (error) {
    res.status(500).json({ message: 'Error fetching blog post', error });
  }
});

// Create a new blog post (protected route)
router.post('/', async (req: Request, res: Response) => {
  try {
    // In a real app, you would add authentication middleware here
    console.log('Creating new blog post:', JSON.stringify(req.body, null, 2));
    
    // Basic validation
    const requiredFields = ['title', 'content', 'author', 'category', 'image', 'readTime'];
    const missingFields = requiredFields.filter(field => !req.body[field]);
    
    if (missingFields.length > 0) {
      return res.status(400).json({
        success: false,
        message: 'Missing required fields',
        missingFields
      });
    }

    // Prepare blog post data with proper formatting
    const blogData = {
      title: req.body.title?.trim(),
      excerpt: req.body.excerpt?.trim(),
      content: req.body.content?.trim(),
      author: req.body.author?.trim() || 'Admin',
      category: req.body.category,
      tags: Array.isArray(req.body.tags) 
        ? req.body.tags.map((t: string) => t.trim()).filter(Boolean)
        : [req.body.tags].filter(Boolean),
      image: req.body.image,
      readTime: req.body.readTime || '5 min read',
      isFeatured: req.body.isFeatured || false,
      publishedAt: req.body.publishedAt || new Date(),
      // The slug will be auto-generated by the pre-save hook
      slug: '' // This will be set by the pre-save hook
    };

    const blog = new Blog(blogData);
    const savedBlog = await blog.save();
    
    console.log('Blog post created successfully:', savedBlog._id);
    
    res.status(201).json({
      success: true,
      message: 'Blog post created successfully',
      data: savedBlog
    });
    
  } catch (error: any) {
    console.error('Error creating blog post:', error);
    
    // Handle duplicate key error (e.g., duplicate slug)
    if (error.code === 11000) {
      return res.status(400).json({
        success: false,
        message: 'A blog post with this title already exists',
        error: 'Duplicate title'
      });
    }
    
    // Handle validation errors
    if (error.name === 'ValidationError') {
      const errors = Object.values(error.errors).map((err: any) => ({
        field: err.path,
        message: err.message
      }));
      
      return res.status(400).json({
        success: false,
        message: 'Validation error',
        errors
      });
    }
    
    res.status(500).json({
      success: false,
      message: 'Error creating blog post',
      error: process.env.NODE_ENV === 'development' ? error.message : undefined
    });
  }
});

// Update a blog post (protected route)
router.put('/:id', async (req: Request, res: Response) => {
  try {
    // In a real app, you would add authentication middleware here
    const updatedBlog = await Blog.findByIdAndUpdate(
      req.params.id,
      req.body,
      { new: true }
    );
    if (!updatedBlog) {
      return res.status(404).json({ message: 'Blog post not found' });
    }
    res.json(updatedBlog);
  } catch (error) {
    res.status(400).json({ message: 'Error updating blog post', error });
  }
});

// Delete a blog post (protected route)
router.delete('/:id', async (req: Request, res: Response) => {
  try {
    // In a real app, you would add authentication middleware here
    const deletedBlog = await Blog.findByIdAndDelete(req.params.id);
    if (!deletedBlog) {
      return res.status(404).json({ message: 'Blog post not found' });
    }
    res.json({ message: 'Blog post deleted successfully' });
  } catch (error) {
    res.status(500).json({ message: 'Error deleting blog post', error });
  }
});

export default router;
